class Constants {
  static const textDescription =
      'Making your own garam masala spice blend can make the difference between '
      'a bland tasting or flavorful chicken curry. Store-bought versions have'
      ' usually lost their flavor while sitting on shelves, which makes garam'
      ' masala a spice blend that is worth making at home.Garam masala is a'
      ' spice blend widely used in Indian cuisine, from curries and lentil dishes to'
      ' soups. Whole spices of cinnamon, mace, peppercorns, coriander seeds,'
      ' cumin seeds, and cardamon pods are toasted in a pan to release'
      ' their aromatic flavors, then ground to a powder Making your own garam masala spice blend can make the difference between '
      'a bland tasting or flavorful chicken curry. Store-bought versions have'
      ' usually lost their flavor while sitting on shelves, which makes garam'
      ' masala a spice blend that is worth making at home.Garam masala is a'
      ' spice blend widely used in Indian cuisine, from curries and lentil dishes to'
      ' soups. Whole spices of cinnamon, mace, peppercorns, coriander seeds,'
      ' cumin seeds, and cardamon pods are toasted in a pan to release'
      ' their aromatic flavors, then ground to a powder Making your own garam masala spice blend can make the difference between '
      'a bland tasting or flavorful chicken curry. Store-bought versions have'
      ' usually lost their flavor while sitting on shelves, which makes garam'
      ' masala a spice blend that is worth making at home.Garam masala is a'
      ' spice blend widely used in Indian cuisine, from curries and lentil dishes to'
      ' soups. Whole spices of cinnamon, mace, peppercorns, coriander seeds,'
      ' cumin seeds, and cardamon pods are toasted in a pan to release'
      ' their aromatic flavors, then ground to a powder  Making your own garam masala spice blend can make the difference between '
      'a bland tasting or flavorful chicken curry. Store-bought versions have'
      ' usually lost their flavor while sitting on shelves, which makes garam'
      ' masala a spice blend that is worth making at home.Garam masala is a'
      ' spice blend widely used in Indian cuisine, from curries and lentil dishes to'
      ' soups. Whole spices of cinnamon, mace, peppercorns, coriander seeds,'
      ' cumin seeds, and cardamon pods are toasted in a pan to release'
      ' their aromatic flavors, then ground to a powderMaking your own garam masala spice blend can make the difference between '
      'a bland tasting or flavorful chicken curry. Store-bought versions have'
      ' usually lost their flavor while sitting on shelves, which makes garam'
      ' masala a spice blend that is worth making at home.Garam masala is a'
      ' spice blend widely used in Indian cuisine, from curries and lentil dishes to'
      ' soups. Whole spices of cinnamon, mace, peppercorns, coriander seeds,'
      ' cumin seeds, and cardamon pods are toasted in a pan to release'
      ' their aromatic flavors, then ground to a powder';
}
